name: ChestTerminal
version: ${project.version}
author: TheBusyBiscuit
website: https://github.com/TheBusyBiscuit/ChestTerminal

api-version: 1.14
main: io.github.thebusybiscuit.chestterminal.ChestTerminal

depend:
- Slimefun